{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-ironsource-adapter",
    "version": "8.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-ironsource-adapter-8.7.0.aar",
          "url": "vamp-ironsource-adapter-8.7.0.aar",
          "size": 86028,
          "sha512": "34e2f129d9ccc9dc46426ed9a85f57a40c09417a5bd189ec59476dd542119fe7ac1069dae9bf30315aec541f5003b6c402c7ff820050f2febe3cdb473514ca01",
          "sha256": "c3d8b230d2700edb2320b175297cb55cfcc959a3d7dafcb7b57a74248cc73072",
          "sha1": "d51ad81b68be089770b9579531398568aa19fc81",
          "md5": "eca65d0c30cde7e00f7a322fb4745fb1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.ironsource.sdk",
          "module": "mediationsdk",
          "version": {
            "requires": "8.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-ironsource-adapter-8.7.0.aar",
          "url": "vamp-ironsource-adapter-8.7.0.aar",
          "size": 86028,
          "sha512": "34e2f129d9ccc9dc46426ed9a85f57a40c09417a5bd189ec59476dd542119fe7ac1069dae9bf30315aec541f5003b6c402c7ff820050f2febe3cdb473514ca01",
          "sha256": "c3d8b230d2700edb2320b175297cb55cfcc959a3d7dafcb7b57a74248cc73072",
          "sha1": "d51ad81b68be089770b9579531398568aa19fc81",
          "md5": "eca65d0c30cde7e00f7a322fb4745fb1"
        }
      ]
    }
  ]
}
