{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-lineads-adapter",
    "version": "2.6.20230607.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-lineads-adapter-2.6.20230607.0.aar",
          "url": "vamp-lineads-adapter-2.6.20230607.0.aar",
          "size": 19335,
          "sha512": "4125ca0639dab98ff198dcc83f970a094116bdaa8402b5182e8d72a5625d4ad9234aa0961b9b4092dd4d19e45960cce5206a7599fe2b5bb5d47c6a8c4deacae4",
          "sha256": "fedbb071186f5b87524f0441c436c8a3ea782565e6137e9e47bfe19418d6c796",
          "sha1": "f7c016123bcbfbc1f6f457b51219c6953015a22a",
          "md5": "6af04a22e4e87badf595a8958ab84c40"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.linecorp.adsnetwork",
          "module": "fivead",
          "version": {
            "requires": "2.6.20230607"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-lineads-adapter-2.6.20230607.0.aar",
          "url": "vamp-lineads-adapter-2.6.20230607.0.aar",
          "size": 19335,
          "sha512": "4125ca0639dab98ff198dcc83f970a094116bdaa8402b5182e8d72a5625d4ad9234aa0961b9b4092dd4d19e45960cce5206a7599fe2b5bb5d47c6a8c4deacae4",
          "sha256": "fedbb071186f5b87524f0441c436c8a3ea782565e6137e9e47bfe19418d6c796",
          "sha1": "f7c016123bcbfbc1f6f457b51219c6953015a22a",
          "md5": "6af04a22e4e87badf595a8958ab84c40"
        }
      ]
    }
  ]
}
