{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-nend-adapter",
    "version": "10.0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-nend-adapter-10.0.0.0.aar",
          "url": "vamp-nend-adapter-10.0.0.0.aar",
          "size": 39242,
          "sha512": "96e3681b204b1f518009062a96d3d0424f3eb4717276b51ff5abca945ecd800ac5c70df1f105b4162921aac4353c580f85bc6c819a0dee3e603f39f7634c79e9",
          "sha256": "cafadd015c3b6bd0fff5e59a2fadeeb7c9f412b2fd3cd1a62c990390319cf23a",
          "sha1": "b428080dedd6ecc5fda734884b46f9f2d5d33153",
          "md5": "43cc3a18ee20497c2239042286858163"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.nend.android",
          "module": "nend-sdk",
          "version": {
            "requires": "10.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-nend-adapter-10.0.0.0.aar",
          "url": "vamp-nend-adapter-10.0.0.0.aar",
          "size": 39242,
          "sha512": "96e3681b204b1f518009062a96d3d0424f3eb4717276b51ff5abca945ecd800ac5c70df1f105b4162921aac4353c580f85bc6c819a0dee3e603f39f7634c79e9",
          "sha256": "cafadd015c3b6bd0fff5e59a2fadeeb7c9f412b2fd3cd1a62c990390319cf23a",
          "sha1": "b428080dedd6ecc5fda734884b46f9f2d5d33153",
          "md5": "43cc3a18ee20497c2239042286858163"
        }
      ]
    }
  ]
}
