{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-sdk",
    "version": "5.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-sdk-5.1.1.aar",
          "url": "vamp-sdk-5.1.1.aar",
          "size": 615775,
          "sha512": "96f086c5fa7129f1c25c51cd64108c368b345aed4c09187f9257271546d5b89973556505612876ce707c2589a86f831a041b193f09268768b2f6dca451df66c6",
          "sha256": "d1eeb4e3dad391bf9b7604897bae0dff9218ab2c4c9bbccbbf904a19bfb09be7",
          "sha1": "d8dd4033b69d5db6edecd33055169e9371051693",
          "md5": "768706e73af32928b3578bbe4b7057a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "17.6.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-sdk-5.1.1.aar",
          "url": "vamp-sdk-5.1.1.aar",
          "size": 615775,
          "sha512": "96f086c5fa7129f1c25c51cd64108c368b345aed4c09187f9257271546d5b89973556505612876ce707c2589a86f831a041b193f09268768b2f6dca451df66c6",
          "sha256": "d1eeb4e3dad391bf9b7604897bae0dff9218ab2c4c9bbccbbf904a19bfb09be7",
          "sha1": "d8dd4033b69d5db6edecd33055169e9371051693",
          "md5": "768706e73af32928b3578bbe4b7057a2"
        }
      ]
    }
  ]
}
