{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-pangle-adapter",
    "version": "6.2.700",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-pangle-adapter-6.2.700.aar",
          "url": "vamp-pangle-adapter-6.2.700.aar",
          "size": 39015,
          "sha512": "458cac1da6be98fb1a3b83b6d87acf2b65c78b027f2ffb8be3cba83ef45357f1e887c4c4c40d36303d5b3bce06fc88ffd644dd11201ad8720cda9309d579a055",
          "sha256": "b6282b7e8fa8783f29350c814e262f12a49739d47d9f58bef35730404a92fe84",
          "sha1": "54c330f89deaa9b71fd9056035a1ac0414b141e9",
          "md5": "e101e53bb4cdb5e570869ec245cbed48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "ads-sdk",
          "version": {
            "requires": "6.2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-pangle-adapter-6.2.700.aar",
          "url": "vamp-pangle-adapter-6.2.700.aar",
          "size": 39015,
          "sha512": "458cac1da6be98fb1a3b83b6d87acf2b65c78b027f2ffb8be3cba83ef45357f1e887c4c4c40d36303d5b3bce06fc88ffd644dd11201ad8720cda9309d579a055",
          "sha256": "b6282b7e8fa8783f29350c814e262f12a49739d47d9f58bef35730404a92fe84",
          "sha1": "54c330f89deaa9b71fd9056035a1ac0414b141e9",
          "md5": "e101e53bb4cdb5e570869ec245cbed48"
        }
      ]
    }
  ]
}
