{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "applovin-vamp-custom-adapter",
    "version": "4.7.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "applovin-vamp-custom-adapter-4.7.1.3.aar",
          "url": "applovin-vamp-custom-adapter-4.7.1.3.aar",
          "size": 8036,
          "sha512": "2d5087f53631622eb4fbcd28b7b60c4aea6e9e63cd518fb6f99ca3feeeeb60546b31ece221f9500d4b92ded49efb960355227624be8d0ca83862eabfc52e398f",
          "sha256": "5193948830afd9fd5d1f6853a33b00182057b7944225b70505655177e0716a91",
          "sha1": "95f080e2a96a07479b71cf45ade0a0bf8414442c",
          "md5": "d132677898d7997f7009d71c1a9eafce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.9.0"
          }
        },
        {
          "group": "jp.supership.vamp",
          "module": "vamp-sdk",
          "version": {
            "requires": "4.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-vamp-custom-adapter-4.7.1.3.aar",
          "url": "applovin-vamp-custom-adapter-4.7.1.3.aar",
          "size": 8036,
          "sha512": "2d5087f53631622eb4fbcd28b7b60c4aea6e9e63cd518fb6f99ca3feeeeb60546b31ece221f9500d4b92ded49efb960355227624be8d0ca83862eabfc52e398f",
          "sha256": "5193948830afd9fd5d1f6853a33b00182057b7944225b70505655177e0716a91",
          "sha1": "95f080e2a96a07479b71cf45ade0a0bf8414442c",
          "md5": "d132677898d7997f7009d71c1a9eafce"
        }
      ]
    }
  ]
}
