{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-lineads-adapter",
    "version": "2.9.2025051900",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-lineads-adapter-2.9.2025051900.aar",
          "url": "vamp-lineads-adapter-2.9.2025051900.aar",
          "size": 10764,
          "sha512": "226466ca12364309566495b9df7a515b892b577dd84ddb21ae1748901efca213cab6e967274d3792dfb9e796ab3aaeccb66b0d0b91dd89c710d088afc2c152c9",
          "sha256": "03af8fe7061fc8a7f069d25d72ef907c6fe19f3961c6439e92bfc337d8fd56b6",
          "sha1": "783d52d31de2a048244b459cd210b65cc4c461d6",
          "md5": "7890380fc19e9901d0d4ad20d9017c53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.linecorp.adsnetwork",
          "module": "fivead",
          "version": {
            "requires": "2.9.20250519"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-lineads-adapter-2.9.2025051900.aar",
          "url": "vamp-lineads-adapter-2.9.2025051900.aar",
          "size": 10764,
          "sha512": "226466ca12364309566495b9df7a515b892b577dd84ddb21ae1748901efca213cab6e967274d3792dfb9e796ab3aaeccb66b0d0b91dd89c710d088afc2c152c9",
          "sha256": "03af8fe7061fc8a7f069d25d72ef907c6fe19f3961c6439e92bfc337d8fd56b6",
          "sha1": "783d52d31de2a048244b459cd210b65cc4c461d6",
          "md5": "7890380fc19e9901d0d4ad20d9017c53"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vamp-lineads-adapter-2.9.2025051900-sources.jar",
          "url": "vamp-lineads-adapter-2.9.2025051900-sources.jar",
          "size": 6165,
          "sha512": "aa6cb75ec0e885de64245406a404a0e35b5dbbbe7cce336a4156a3c01ae92db5307c33350941b261c0682f4f3774a586b386f8c0ff66f31020e3d4744a335acf",
          "sha256": "17ad01bbf5b2f48f7eecec6550f6278672695485dfdffee73071b26211a10f87",
          "sha1": "152bb0018ddd240d10e3b123852f98fb59135067",
          "md5": "4cbf142f267497166e871b4d19df9411"
        }
      ]
    }
  ]
}
