{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-pangle-adapter",
    "version": "5.4.1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-pangle-adapter-5.4.1.1.0.aar",
          "url": "vamp-pangle-adapter-5.4.1.1.0.aar",
          "size": 39451,
          "sha512": "39368a50f0480dbb3c238ae2063e7af603a7fdbd9399bae706ba25babbfd7c35efb7d8f4e03b070a3712bf568f8381bb65d5b84a8134853ebbe219052c42b4d2",
          "sha256": "a507c2c31e287f6e3f51408cc21292fb7f10035150e88d2a1063ee206f75756f",
          "sha1": "57e633d798eb4ecda8bc1ce19849dc13ad6e926c",
          "md5": "3496660bb4b08e64beed9af977b06928"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "ads-sdk",
          "version": {
            "requires": "5.4.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-pangle-adapter-5.4.1.1.0.aar",
          "url": "vamp-pangle-adapter-5.4.1.1.0.aar",
          "size": 39451,
          "sha512": "39368a50f0480dbb3c238ae2063e7af603a7fdbd9399bae706ba25babbfd7c35efb7d8f4e03b070a3712bf568f8381bb65d5b84a8134853ebbe219052c42b4d2",
          "sha256": "a507c2c31e287f6e3f51408cc21292fb7f10035150e88d2a1063ee206f75756f",
          "sha1": "57e633d798eb4ecda8bc1ce19849dc13ad6e926c",
          "md5": "3496660bb4b08e64beed9af977b06928"
        }
      ]
    }
  ]
}
