{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-unityads-adapter",
    "version": "4.13.100",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-unityads-adapter-4.13.100.aar",
          "url": "vamp-unityads-adapter-4.13.100.aar",
          "size": 20320,
          "sha512": "04450a9f7dbaaadb118a125d94b12665a7b7dc3d5404170d7436880bfe4db27696c3352b320e4e1790a5c960019b36c65daf9d25eb5bea7797ac11a763b0e74d",
          "sha256": "ab013cf21a72f50b734a015430c130bec28af758f67ef5de905e88553facf15f",
          "sha1": "243829c29ab60c7a60ed183e0ee5f072a1e93c47",
          "md5": "37fdffb6358d1970e21d280ca5dd30c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-unityads-adapter-4.13.100.aar",
          "url": "vamp-unityads-adapter-4.13.100.aar",
          "size": 20320,
          "sha512": "04450a9f7dbaaadb118a125d94b12665a7b7dc3d5404170d7436880bfe4db27696c3352b320e4e1790a5c960019b36c65daf9d25eb5bea7797ac11a763b0e74d",
          "sha256": "ab013cf21a72f50b734a015430c130bec28af758f67ef5de905e88553facf15f",
          "sha1": "243829c29ab60c7a60ed183e0ee5f072a1e93c47",
          "md5": "37fdffb6358d1970e21d280ca5dd30c7"
        }
      ]
    }
  ]
}
