{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-lineads-adapter",
    "version": "3.0.100",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-lineads-adapter-3.0.100.aar",
          "url": "vamp-lineads-adapter-3.0.100.aar",
          "size": 11944,
          "sha512": "5e09136195428af88ddeb7bd6bd8187a309b22190a8b2936dbf3447f3537286976e395870b09475870fcf4f8c11b97f4ab3477b3d65d7a743179828c07e05115",
          "sha256": "c6d5a3250fcef3d4dd019750133af4fd038b40532edb5a4c63e04052b3c0abc3",
          "sha1": "cdac6b6ab2717c015dcbd544401af569333470e6",
          "md5": "828fa2fb75329738c47204dd50743779"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.linecorp.adsnetwork",
          "module": "fivead",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-lineads-adapter-3.0.100.aar",
          "url": "vamp-lineads-adapter-3.0.100.aar",
          "size": 11944,
          "sha512": "5e09136195428af88ddeb7bd6bd8187a309b22190a8b2936dbf3447f3537286976e395870b09475870fcf4f8c11b97f4ab3477b3d65d7a743179828c07e05115",
          "sha256": "c6d5a3250fcef3d4dd019750133af4fd038b40532edb5a4c63e04052b3c0abc3",
          "sha1": "cdac6b6ab2717c015dcbd544401af569333470e6",
          "md5": "828fa2fb75329738c47204dd50743779"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vamp-lineads-adapter-3.0.100-sources.jar",
          "url": "vamp-lineads-adapter-3.0.100-sources.jar",
          "size": 6277,
          "sha512": "80dffd073b9c9145649e9c1fa2bc3337dd10a615c5429b4db436255635a4226d69323ebb4e1290b2a81b99ef79fe8d35143f40cf9da336b6d1627ff1e02d835b",
          "sha256": "c28fbe65c2b747c1440d1e5756be45bf72bf654745f94bf6f5699db693cc48e8",
          "sha1": "41da98829231de8874bfebd4a526bd4da7e338b3",
          "md5": "26d3a1a6c7edc710c588d436966ba078"
        }
      ]
    }
  ]
}
