{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-unityads-adapter",
    "version": "4.9.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-unityads-adapter-4.9.1.1.aar",
          "url": "vamp-unityads-adapter-4.9.1.1.aar",
          "size": 20570,
          "sha512": "d7f08a530043477b971211cac60ac826ca6bb35ced17027ef6574cbc3ee0e98503d50d08b343e97de4262d572cc6b97512fc25f089a49f8f43c911a21c858d5e",
          "sha256": "c022b5621a53ce9eee4d083650e863124ad28a5f8b12532aaea3ce5fc5d953d6",
          "sha1": "564c282c3ceeeb5996f8db8653e2be61fd85a60c",
          "md5": "faa222621632ae6cb5b75d260b810e79"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-unityads-adapter-4.9.1.1.aar",
          "url": "vamp-unityads-adapter-4.9.1.1.aar",
          "size": 20570,
          "sha512": "d7f08a530043477b971211cac60ac826ca6bb35ced17027ef6574cbc3ee0e98503d50d08b343e97de4262d572cc6b97512fc25f089a49f8f43c911a21c858d5e",
          "sha256": "c022b5621a53ce9eee4d083650e863124ad28a5f8b12532aaea3ce5fc5d953d6",
          "sha1": "564c282c3ceeeb5996f8db8653e2be61fd85a60c",
          "md5": "faa222621632ae6cb5b75d260b810e79"
        }
      ]
    }
  ]
}
