{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.supership.vamp",
    "module": "vamp-ironsource-adapter",
    "version": "7.9.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "vamp-ironsource-adapter-7.9.0.0.aar",
          "url": "vamp-ironsource-adapter-7.9.0.0.aar",
          "size": 78392,
          "sha512": "7425ce4f7fadd76f84821d5ef4f15d0a2c4dcc89689b3880e3d3ee350391fab16c0f0ceba6d79b9c70e2b8d68c8a995e2287720476ea1307ea8caabaf5c51e08",
          "sha256": "7a96da98386079c32526dc8f1cd179666edb8e4e2d88bbd7639c4e55765a1cc5",
          "sha1": "e56d1608b8350c4def31d4b91bb072bdd8e2be27",
          "md5": "398c2cad06d83e92c0c7673930834720"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.ironsource.sdk",
          "module": "mediationsdk",
          "version": {
            "requires": "7.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "vamp-ironsource-adapter-7.9.0.0.aar",
          "url": "vamp-ironsource-adapter-7.9.0.0.aar",
          "size": 78392,
          "sha512": "7425ce4f7fadd76f84821d5ef4f15d0a2c4dcc89689b3880e3d3ee350391fab16c0f0ceba6d79b9c70e2b8d68c8a995e2287720476ea1307ea8caabaf5c51e08",
          "sha256": "7a96da98386079c32526dc8f1cd179666edb8e4e2d88bbd7639c4e55765a1cc5",
          "sha1": "e56d1608b8350c4def31d4b91bb072bdd8e2be27",
          "md5": "398c2cad06d83e92c0c7673930834720"
        }
      ]
    }
  ]
}
